// Code generated by "stringer -type=DBEngine"; DO NOT EDIT.

package dbapi

import "strconv"

const _DBEngine_name = "SqliteMariaDB"

var _DBEngine_index = [...]uint8{0, 6, 13}

func (i DBEngine) String() string {
	if i < 0 || i >= DBEngine(len(_DBEngine_index)-1) {
		return "DBEngine(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DBEngine_name[_DBEngine_index[i]:_DBEngine_index[i+1]]
}
