// Code generated by "stringer -type=SymbolSetType"; DO NOT EDIT

package symbolset2

import "fmt"

const _SymbolSetType_name = "CMUSAMPAIPAOther"

var _SymbolSetType_index = [...]uint8{0, 3, 8, 11, 16}

func (i SymbolSetType) String() string {
	if i < 0 || i >= SymbolSetType(len(_SymbolSetType_index)-1) {
		return fmt.Sprintf("SymbolSetType(%d)", i)
	}
	return _SymbolSetType_name[_SymbolSetType_index[i]:_SymbolSetType_index[i+1]]
}
