package symbolset

// NewNSTSymbolSet is used for testing
func NewNSTSymbolSet() (SymbolSet, error) {
	name := "NST nob sampa"
	symbols := []Symbol{
		Symbol{"@", Syllabic, ""},
		Symbol{"A", Syllabic, ""},
		Symbol{"E", Syllabic, ""},
		Symbol{"I", Syllabic, ""},
		Symbol{"O", Syllabic, ""},
		Symbol{"U", Syllabic, ""},
		Symbol{"u0", Syllabic, ""},
		Symbol{"Y", Syllabic, ""},
		Symbol{"{", Syllabic, ""},
		Symbol{"9", Syllabic, ""},
		Symbol{"A:", Syllabic, ""},
		Symbol{"e:", Syllabic, ""},
		Symbol{"i:", Syllabic, ""},
		Symbol{"o:", Syllabic, ""},
		Symbol{"u:", Syllabic, ""},
		Symbol{"}:", Syllabic, ""},
		Symbol{"y:", Syllabic, ""},
		Symbol{"{:", Syllabic, ""},
		Symbol{"2:", Syllabic, ""},
		Symbol{"9:", Syllabic, ""},
		Symbol{"{*I", Syllabic, ""},
		Symbol{"9*Y", Syllabic, ""},
		Symbol{"A*I", Syllabic, ""},
		Symbol{"E*}", Syllabic, ""},
		Symbol{"O*Y", Syllabic, ""},
		Symbol{"o~", Syllabic, ""},
		Symbol{"n=", Syllabic, ""},
		Symbol{"l=", Syllabic, ""},
		Symbol{"n`=", Syllabic, ""},
		Symbol{"l`=", Syllabic, ""},
		Symbol{"}*I", Syllabic, ""},
		Symbol{"a*U", Syllabic, ""},
		Symbol{"@*U", Syllabic, ""},
		Symbol{"e~", Syllabic, ""},
		Symbol{"3:", Syllabic, ""},
		Symbol{"a", Syllabic, ""},
		Symbol{"a:", Syllabic, ""},
		Symbol{"U:", Syllabic, ""},
		Symbol{"V", Syllabic, ""},
		Symbol{"U4", Syllabic, ""},
		Symbol{"I@", Syllabic, ""},

		Symbol{"p", NonSyllabic, ""},
		Symbol{"t", NonSyllabic, ""},
		Symbol{"k", NonSyllabic, ""},
		Symbol{"b", NonSyllabic, ""},
		Symbol{"d", NonSyllabic, ""},
		Symbol{"g", NonSyllabic, ""},
		Symbol{"f", NonSyllabic, ""},
		Symbol{"v", NonSyllabic, ""},
		Symbol{"h", NonSyllabic, ""},
		Symbol{"j", NonSyllabic, ""},
		Symbol{"s", NonSyllabic, ""},
		Symbol{"l", NonSyllabic, ""},
		Symbol{"r", NonSyllabic, ""},
		Symbol{"n", NonSyllabic, ""},
		Symbol{"m", NonSyllabic, ""},
		Symbol{"N", NonSyllabic, ""},
		Symbol{"t`", NonSyllabic, ""},
		Symbol{"d`", NonSyllabic, ""},
		Symbol{"s`", NonSyllabic, ""},
		Symbol{"n`", NonSyllabic, ""},
		Symbol{"l`", NonSyllabic, ""},
		Symbol{"S", NonSyllabic, ""},
		Symbol{"C", NonSyllabic, ""},
		Symbol{"tS", NonSyllabic, ""},
		Symbol{"dZ", NonSyllabic, ""},
		Symbol{"w", NonSyllabic, ""},
		Symbol{"x", NonSyllabic, ""},
		Symbol{"T", NonSyllabic, ""},
		Symbol{"D", NonSyllabic, ""},
		Symbol{"r3", NonSyllabic, ""},
		Symbol{"Z", NonSyllabic, ""},
		Symbol{"z", NonSyllabic, ""},

		Symbol{"%", Stress, ""},
		Symbol{"\"\"", Stress, ""},
		Symbol{"\"", Stress, ""},
		Symbol{" ", PhonemeDelimiter, ""},
		Symbol{"$", SyllableDelimiter, ""},
		Symbol{"-", CompoundDelimiter, ""},
	}
	return NewSymbolSet(name, symbols)
}
