// Code generated by "stringer -type=Field"; DO NOT EDIT

package line

import "fmt"

const _Field_name = "OrthPosMorphWordPartsLangTrans1Translang1Trans2Translang2Trans3Translang3Trans4Translang4Trans5Translang5Trans6Translang6LemmaParadigm"

var _Field_index = [...]uint8{0, 4, 7, 12, 21, 25, 31, 41, 47, 57, 63, 73, 79, 89, 95, 105, 111, 121, 126, 134}

func (i Field) String() string {
	if i < 0 || i >= Field(len(_Field_index)-1) {
		return fmt.Sprintf("Field(%d)", i)
	}
	return _Field_name[_Field_index[i]:_Field_index[i+1]]
}
